name: 'OPRF Asset Updater'
description: 'A workflow which automatically updates OPRF standard asset files from the OpRedFlag repository'
author: BobDotCom
branding:
  icon: box
  color: gray-dark
inputs:
  branch:
    description: 'Local branch to checkout and apply changes to'
    required: false
    default: ''
  repository:
    description: 'Location of OpRedFlag asset GitHub repository, in User/Repo format'
    required: false
    default: 'NikolaiVChr/OpRedFlag'
  repository-branch:
    description: 'The branch of the OpRedFlag repository to use'
    required: false
    default: 'master'
  version-file:
    description: 'Location of local versions.json file'
    required: false
    default: "oprf-versions.json"
  include:
    description: 'Files to update, separated by commas'
    required: false
    default: "*"
  exclude:
    description: 'Files to skip, separated by commas'
    required: false
    default: ""
  compatibility:
    description: 'Compatibility level, will only allow updates of this level or lower'
    required: false
    default: "minor"
  strict:
    description: "Fail if local file versions are newer than remote"
    required: false
    default: "false"
  commit_message:
    description: "The title of the commit that is made"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ inputs.branch }}
    - uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    - name: "Install requirements"
      shell: bash
      run: python -V && pip install --upgrade pip && pip install -r ${{ github.action_path }}/requirements.txt
    - shell: bash
      run: echo ${{ inputs.commit_message || 'Auto-Update Shared Files' }} >> ${{ github.action_path }}/commit.txt
    - name: "Update assets"
      env:
        PYTHONUNBUFFERED: "1"
      shell: bash
      run: oprf update -r "${{ inputs.repository }}" -b "${{ inputs.repository-branch }}" -v "${{ inputs.version-file }}" -i "${{ inputs.include }}" -e "${{ inputs.exclude }}" -c "${{ inputs.compatibility }}" ${{ inputs.strict == 'true' && '-m' || '' }} >> ${{ github.action_path }}/commit.txt
    - name: Set commit message
      id: commit-message-step
      shell: bash
      run: |
        echo 'commit_message<<EOF' >> $GITHUB_OUTPUT
        cat ${{ github.action_path }}/commit.txt >> $GITHUB_OUTPUT
        echo 'EOF' >> $GITHUB_OUTPUT
    - uses: stefanzweifel/git-auto-commit-action@v5
      if: "${{ github.event_name == 'workflow_dispatch' }}"
      with:
        commit_message: ${{ steps.commit-message-step.outputs.commit_message }}
    - uses: stefanzweifel/git-auto-commit-action@v5
      if: "${{ github.event_name != 'workflow_dispatch' }}"
      with:
        commit_message: ${{ steps.commit-message-step.outputs.commit_message }}
        commit_author: 'github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>'
